### ISSUE TITLE
关于网站平台JS代码被加密问题？

### ISSUE THREAD

**Issue by sunsikai** [BB-fat/InvoiceSpider#1]
你好，按照你的教程学习，我成功查询到了发票信息。但在深入学习过程中，发现发票查验平台的JS代码是加密过的，而你的教程里面展示的js代码却是源码。这让我很疑惑，不知道是该平台在后来对其JS代码进行的加密，还是你有特殊解密JS代码的方法，请问方便指导一下这一点吗，感激不尽！

**Comment by BB-fat** [comment]
js加密混淆的方式有很多，我的破解方法是利用chrome的调试工具打断点、单步执行的方式拿到源码，具体操作步骤在我的博客这一段有描述。https://www.fatech.online/articles/2019/08/31/1567224350566.html#b3_solo_h2_2
如有更多疑问欢迎提出来。

**Comment by BB-fat** [comment]
我看到了你在我的博客下面的评论，我已经把项目更新了，现在v2.0兼容最新版本的查验平台，还加入了比较初级的验证码识别模块，你可以安装好依赖尝试一下。
至于你说的关于js混淆的问题，的确有一部分代码是无法查看的，但是那不是核心算法，由于我升级了最新的Chrome，已经无法再打开那个网站，我就通过Firefox测试了一下，通过打断点单步执行的方式依然可以看到核心算法，也就是虚拟的代码。
![](https://tva1.sinaimg.cn/large/0082zybply1gbsskh3i3qj31c00u04qp.jpg)

**Comment by BB-fat** [comment]
@sunsikai 没有问题我就关闭这条issue了

**Comment by sunsikai** [comment]
我这边已经没有问题，感谢您的解答，这条issue可以关闭了
