### ISSUE TITLE
获取不到验证码，今天官网好像改版了

### ISSUE THREAD

**Issue by shimachao** [BB-fat/InvoiceSpider#10]
官网加了反调试，仅仅输入发票代码和号码获取不到验证码了。而且加了反调试

**Comment by BB-fat** [comment]
Hi，
感谢你关注我的项目，在你的提醒下我发现了这个问题，增加的反调试让我的Firefox变得卡顿，后来我使用Safari并关闭了中断功能，成功抓包得到了更新的内容，其实就是将版本号进行了一次改动，不得不说官方的程序员真的有点懒，我已经更新了代码，并且测试通过。
祝顺利！

**Comment by BB-fat** [comment]
反调试的问题我已经有了对策，欢迎来看我这篇博客：[【爬虫技术】破解js反调试](https://www.fatech.online/articles/2020/04/05/1586069632742.html)

**Comment by BB-fat** [comment]
没有问题我就关闭这条issue了？

**Comment by shimachao** [comment]
> 没有问题我就关闭这条issue了？

可以关闭了
