### ISSUE TITLE
4月1日，国税局又更新了

### ISSUE THREAD

**Issue by fengfumin** [BB-fat/InvoiceSpider#12]
这次获取验证码参数里多了个flwq39，感觉是用base64加密的，但不知道用哪些数据加的密，现在js代码都加密了，看都看不懂

**Comment by BB-fat** [comment]
我今天已经更新了项目，已经适配了最新的版本，你可以更新一下试试，博客会在稍后更新。

**Comment by fengfumin** [comment]
好了谢谢，原来改了版本号，V2.0.02_002，之前就改了前面的2，后面还有个2没注意

**Comment by BB-fat** [comment]
我在尝试找一个思路破解混淆的js，如果有什么点子欢迎提出来一起交流
