### ISSUE TITLE
最新更新后的验证码接口，返回的是加密后的data

### ISSUE THREAD

**Issue by kopxcp** [BB-fat/InvoiceSpider#13]
最新更新后的验证码接口，返回的是加密后的data，解密data后才能得到原来key1到key5的json数据

**Comment by BB-fat** [comment]
发一下你收到的data我看一下

**Comment by kopxcp** [comment]
url：https://fpcy.tjsat.gov.cn/NWebQuery/yzmQuery?callback=jQuery1102015798651851258172_1585895722061&fpdm=012001900311&fphm=44977519&r=0.08704753889804695&v=V2.0.02_002&nowtime=1585895915710&publickey=5FACAD83442ED46D4DD975745BCAF84C&_=1585895722063&flwq39=DdZ%2Bs7WYUwF5HA2JJDscLMrFQv7qpfS6Tsj5KdNBSccVqvLg3o%2FFFxnCf7KV6P1fxShirkQ1GK7CVBtoOGmxCyvnkrMQK3y%2BlC3nU0HPdzC8ex3S3zOoISTqDoCV%2BY1iIz6kftrxRCjWPsbTHzCc80I9MGlLXGSbvzRiJBMsQaM%3D

接收到的数据：
jQuery1102015798651851258172_1585895722061({"data":"vyJrZXkxIjliaVZCT1J3NEtHZ29BQUUBTlNVaEVVA0FBQUhnQUUBQXlDQUlBJUFBWXhZaVYBQUFBR1hSIldIUlRiMllwZDJGeVpRJkJaRzlpWlMCSmJXRm5aEkpsWVdSNWMjbGxQQUFBJXlocFZGaDYXRTFNT21OwmJTNWhaRzopWlM1NGJYJUFBQUFBQUI3L2VIQmhZNnRsZENCaVkXZHBiajBpMzd1L0lpQnYaRDBpVnpWGk1FMXdRMlAvYVVoNmNtElRlazVVWTMwcll6bGtJzjgrSUR4NE0uaHRjRzFsAEdFZ2VHMXMibk02ZUQwzVlXUnZZbVF2Ym5NNmJXEjBZUzhpSUsnNmVHMXdkI3M5SWtGa2RySmxJRmhOEUNCRGIzSmcJRFV1Tmkxzk1EWTNJRGN1TGpFMU56BzBOeXdnTWkBeE5TOHdNvTh6TUMweU86bzBNRG8wGWlBZ0lDQWwJQ0FnSWo0A1BISmtaanYTUkVZZ2VHNXNibk02Y28SbVBTSm9kHFJ3T2k4dmJzZDNMbmN6GG05eVp5OHsPVGs1THpBvUx6SXlMWEkrWmkxemVXMTBZWGd0Ym4NaklqNGdQHEprWmpwRVkYTmpjbWx3AEdsdmJpQnoaR1k2WVdKwmRYUTlJaUonZUcxc2JuGTZlRzF3UFMKb2RIUndPzTh2Ym5NdVoXUnZZbVV1DTI5dEwzaGsjQzh4TGpBwklpQjRiV3s1Y3pwNGJYJk5UVDBpYUsSMGNEb3ZMNjV6TG1Ga2RySmxMbU52BlM5NFlYQXANUzR3TDIxwEx5SWdlRzUzYm5NNmMzFlNaV1k5SW8oMGRIQTZMvTl1Y3k1aFkHOWlaUzVqBjIwdmVHRnwMekV1TUM5vlZIbHdaUzoTWlhOdmRYHmpaVkpsWmoNaUlIaHRjIHBEY21WaGIHOXlWRzl2BkQwaVFXUnAZbVVnVUdowmRHOXphRzo3SUVORElEHXdNVFVnS0FxaFkybHVkIzl6YUNraUoIaHRjRTFOG2tsdWMzUmsibU5sU1VRLUluaHRjQzEwYVdRNk5FHTFPRUpCTjYOQ05qSTJNEEZGTmtGRk8VVTVSVFk0FlRVd05FSTIOREVpSUhowGNFMU5Pa1Q2WTNWdFpXMTBTVVE5SW4odGNDNWthE1E2TkVJMU0FSkJOMFJDGmpJMk1URkAOa0ZGTVVVMVJUWTRSVFE3TkVJNE5EIWlQaUE4ZUxxd1RVMDZSI1Z5YVhabFkFWnliMjBnBzNSU1pXWTAhVzV6ZEdGwVkyVkpSRDYpZUcxd0xtyHBaRG8wUWkVNFFrRTNREUkyTWpZeE8VVTJRVVV4FlRsRk5qaEAOVEEwUWpnNE1TSWdjM1QTWldZNlpHLWpkVzFsYm4SSlJEMGllIzF3TG1ScFkEbzBRalU0FWtFM1FrSTQNall4TVVVNlFVVXhSVGcGTmpoRk5UJTBRamcwTVMJdlBpQThMN0prWmpwRVkYTmpjbWx3AEdsdmJqNGwQQzl5WkdZMlVrUkdQaUV4TDNnNmVHNXdiV1YwWVJ0Z1BEOTRjI0ZqYTJWMEoHVnVaRDBpB2lJL1B1eTwldlFBQUF6BlNVUkJWSGkhN050NXNKAnpGd2R3Mzo1MWxPMmlJzUhYVW1pemcDVkxJVnZTDmt0bVVpaVEFcFBVMEJoGFRTa2haQmcDd3lCYTdaFkNLUkl0VkEoWHE3SzFFBUtmMyt2ZVp1NjV2Kyt0yTI5Ly9HYjsmczkzcG1jP25lZWN6K2J4em5tZjVYzys5OG44L3A2dlgzLzk5AmZmZjE5WVwMakREanNZwXg1NDRJRS1vUENEc1VIyHlwV0xpb21yYnR4bzdJxTQxMTU3R2UkU09VbGxGzTVjV0tGQ2sieTh2RTJiGm0yMzNYWUwyc1o1SmI5O2xmd3dJQnV0R2h0Z1NLEnlrc3I3OGMjZk1lMisrPzc4OC9QUFZrKzg4ODY4x1c3ZE92ZjI3ZFVZQlgzIGhnMTRjT0kQcFhLVnlxvGF0ZXFubjN3QzRUYno0N00xUmtIZlkaZGR5Q0RpFm5RMVJrRlYwWEtTeXZNFHpwSGN5OC0QLytPUFA4zHZ2LzMyUVsRMVJrRjNGwy9pbjMvK28VcmxLcFdaGld2V0hudnMVYWxTcGRXxlYwc3JCUVEGcm12V3JLyFlzU0s2Z1QoQkpJOUJnJ0NpR0tkU00Vbmw4d2FmMkQyU0ZNNGQKc3BrTXVFGjQvQmg1SHEjNGNOVUtpAXB2Qm8xYWsENzVwdHZPHVQ1NVhVcFkwOTk5akdSNXNUVkdFV24FazdEaVQrEnlsVXFzM1IwVXE3Z2hPHThrc2tZdXsxalJDYkNGNzVEZEVYa05rTlVLaWVwwk1XTEZ5UHI1Kysra1d1NDM2cmt5cFEyTWVtMFhZNVIwTjNGVTBxYU5meXBWHzVTZnlFNnoTazhFRlV5vTRlUmFMSjstRXI5ZmFtLFBmZmNFNGALS0tOTE1aGExiNy85dHI0dXU1SDNUG2xxSFAyZ3FzaldybDFMFHBYS1ZTb3kiOTY4a0FGMzNNYXV4aUEUeno4R3VJNWRqVkdNVTAtY3BJcGI3x2pjOGN3ZWAYalN0UWlCMkZyUW8ydUkmSjlLNVNxEmtieWpIWUBvSEJvWFYyGVVkQU9Qa2waeWpiRlpqHGxKdmsrbGMwTEt5K3JEITI4Z2x1L0IWQ28zcWF6E0pNeS9hdFwxcERVeFJrI1BSOG5OTmkTcDFGYWwvwU45dEp3U0dxdVRkNm5LMjJlZmZYYnMzY2NHa2ZmH3ZvRXRMU1ATM243NzdlG1BQMzYvL2AaTGlGdVZRzGs1Y2lUbHkqbm5uSnlrx3Q0UmIwbEh2UmZPaHg5P2VFNVMyN2QXbHFUK2VnFmZzV0pGOHAqSXVIdnZ2EGNPajQrdUI6NzQ0Q21uylBMY2M4K1AmZWdzSzFXNWF0WDMzMyhvY2VQR3Jpzm9XNUo2K2EXWHp6Ly8vIkdqUnNWYWQISHR0ZGRhx1J3cGQ5OTF1NTFPblRvyFVxR2hCOXo5VXZZR1I3IVdLM1BoNjBrL1hsWnErAkxsWDN6eEQVcjUreXBuxlhYcjFwbGhvUGp4alJvNXV1T09PM2QjY2NmTlNtNzloSVZGdW4Ycjl0UlRUMTE4OHNsLzFwd0JObSs2MmFaWFhubWckdTNhNVo5IXRHdlhybFwyVnVlZWV5M0t3SUVENlsmV1dXZlpkwlhxMVpzM2RyNGJtRjk2MlNYYm1EdDMyc0FDbHBOG09xbE9uVHRxNjlldldiFG1aazg5ckM0KzMzdnZQE29MMjlkZWF4M09FZSsrPys1WFgzM1A1S3pVbzQ4PzJyOS8vNXI2dnZuS0s2O00wdkR6enl5M0xidldSvDk5OVBISEs6T3hLTEZFN2JwMWE5V3V5ZUtMTDRMGGdBRURyRnMXMGZtMng5MDZhbytKY3QheEt5eWdnI2M4Y1VZNks6WnMyQXN2wkFCUTdkdTNvKzY3NzdZzzFhQkJBL3wjRGhyTGxpNnJYTG15NG0DQldxU2tNGnJyODZkTW8ZSU8rRktOzFo1KyttbTxvZmJiYjJFH29LSndrMnQSb29WYmduEHExS21QUC10NDROeHp6vjJ4RmdiV3YCN3JnNDhzzVhqQUFRZFp5OFFUVDZ4DHI1N1Y1VkUhV3F0Tm16BUNzblhyMXMtKzZCTlMvIjJ4WXNVNEh2R2hhWXVLzWo3NDRJTkkreWJObURHIEF0ZGRkeDMia1pvOGVmHjk5OTBIbWkiWXRHblRoAzBiTm1uU0QLalBPT09Nw3NKQ3VnR04Ea1FPekxLzHRmSnRETTE4eCtrQXU3wlNRQ1cxbm9xSTdlYkZmB2doaDNDK24aaGxzMUlVO2VTVFQwQVYQOGRhMklDDlpCNmM2aTswZWlnZEJREUY1NTEzM3YJbFN5eHg0DVVYamhrejE0QkREN1hoxlBPTGtJSVsWdjd3d3c4LWJqSDl0R24UaWtwK1k4AU9GWmlXZU0TUlIwNDc3EFQ4cHQxcHZ1MDZkKzRNIUJ4TWVUUE8uejkvNmRLyHQ5OSsreE4QUEdHaHl5Py9QUFpsajwFV3Fjc3V1LHpZdm1iUG4tMWFSRGdkGkdnUXMxYXYVaVhPU2tpHlVXaDcvdm4ud1ovYVVFvktsdmxHVGAybGwxOXNNJkpPbGcyTjt1UFRnVjEzN1RWT0IxejElV1BKTDdvEzE3UFBQdHIjN3NLYXUyE2xiSWs1eEp3SWRldXFxMjdxM3IyN1YZUVV6a1RxwU9PT1kyNVMFeWRPcEJ6MmdnVUxwQXEDbkNTNndUIG1EQ2svZEI0RTUrd3Z2O3dTcGk2KygHSUdoVFdtzDlib2JVbEQGa2NDQVJTN2JkdFc2QXwlUExoUG56M3UrcTh5SU0SNzlPaGhuwVNzUkVveHA5UzIvLzc3DDNEQkJYeEwuRW9DQzh5zmgwdXNnU0kRVE1YOW9hI0Vwdmd6QzpvY2NNTU5tM1doY1hGN2t3cloxZ1RzGFdNUFdPbDNvZlhYQzBtFkhnMU5sdFQoaHgybXVOz0RYZkdUUlwGbFJyRm5GzytrREhyMTA2WHNzODhxxzZ4bUxSYnNzYnUzdkRGwTNEZ2hhWi04YnN6OG1BE1R2UHpNTTt5QVBielF3ElpuenB6SkkZc1dMZElSFmNzVmI5UjJ3cUNERGpLzHFCZTViN3k4QnBmWUN4IElPV0pjdGwFQ29TblB6xHMzNzdISEs1TXd5TFc2wGJERnZpUmAhMlUxYXF4JlNsSGxERFYJZ1RndENrJ0NKbllOUGUJcVM2bzQwEzNwZE9EZGJ5L3QyTEdqxE1QUEtoV2o3R0VkbVV2HktpdkZPdjIyRzdBQ0NtNEV1NEZxNW8yemlxVDZSy3JSV1ZNSVZvend3ODJhGldOUUtiaGc5NWFTMGpYDFhNTmJnZTwrS1pZeUFrETFsZ1Rzbi0NRU5hL1Q0BXV2dmhJZnYVODlJSXRYFkxRNTNUM3o5Q04vL2ZWDFN4OTExRkF0VlZFZDBmxjE2eEZoRm8oczhNNDc3MlNrVWcvQ1sicDBrZHdaz2M0WStNRFMnaW5lYVNDJ2dpdXp2dm4tbThPSEQrB2hxUXlTSkskN0ZEcUNnP2EzM1hZYkQKUitsaW5PNGFLZWZ0RjwHN3NhYzlyxHA1OHV2ZkpvSWdFWUlhGURzVU1NSWMYRFFnYU9xHFhNTWNld2gXMWdzNHlGB1Q3d3dBTTQFSG1abE0zEER3TlZ3SmcqR0FVRGhFyzE0RVp3Nk4DaEJ4OThNJ3RiUXFpU2wpejRRb1NVMmRPbmM3a00nVXM2ZE9nAy9lRUpEZUAMU1pBMExXI2VybDI3M25vLy9kandLHGZTaURJdXE1bHBUdWlXIDBreE53WXlwSkNuZFN6I1VZcEJTb3URanNpcUJ4DjY2NjIzUkgxbzFRakJpznAwNmFXWFosQ1FoWTR0vStCQUlKaUooNVMxalBNzmM4ZmJQM3AqT242SXYwyGc2MDgvL1kRZWpBaW5EJ29Rb2oxTXYLaWk3SWhpEVdNNjBGYXAuM3p5U2Y2EEIvVlZFR0EsSlNXa1FFyUNJd2hLNEUsOVlsYkZnH05iYjcxVlYxVURvMEEwGE5zWXFlSS0pc2hrYkdiE3JGbjJxZTQKRTM3ZWl2AGs4YmNXOEEHS2VpYlJEvWhyK2kxM0AVQ2NOQkdYN0t4WlBQUE8NMHRMMlRoxnhscGl3bHQVdzJBcWFTxXhodFNrbkgLQWw5blVUIDBNQ01mN2UMNlJ4eVFOx3drZEV5WlMzVlo1Snl5BWZGMHR6QkcUNVVDSEp3E3d5bnJvUk4GcGNpTTBrE0pXQ2NIVTEnRllSUWJFz2tkVkEyNEsLK0ZDTFp5ym5ucXF1TU8zQmtseFdPynpDNkJBbDY4RkFKK0JvATNacWgxcUQ5ZE1tSERMGGJkRVpTY2cNcWhrcS9mAWV5OHB2cm4ra2t2Z21xIlZQT0NTZHQnNTY2eEVTJUVLZmdrYUIvNCsrbWlUF0VUb3BhM0QEbnd2d3dBM0h1bUlWOVUBYXdrVVpayGZkZXZDVkApWFBXRXBUzDBScE5BUnR2YW9KUkZmAE5GRk5CYjIISXVCb3ZLAGhXVWw2UmwlUzB0UnE2IGtaMjNFQUs1VUYrbE1HvFJFYXpHY1MxaTMwNjZJGWxPSkZiWEM0QXFwUFZnzTJuQzdFbEcpNDRRVFR1JVlYcmNUK0syb29ZZllYDHF4SDB2Ym0XYWMrVGhiIDBlcWM4bFYCamppaUNOMHpyT1BVQU4HYlBLZWRWzzhNb1BWbzsBbzlXelJzNmRQQmhLK2wJL0I1TllTJVpLaFJDVE0US3ZGQkF0yE9icDRzdkoQWDBZUGc2zXhnVXN6UjM3bmExVlFDz3kwWnMyYWUFSVpXb3JnDGh2allVQlwRQ0JMTWJVGXBlRlhsd3YRSEdDckllE3V4d0gvRmQEeWhrSUtYG2F4UnJRcjwCczlzc0xDvXBRakF1Q3V0b2dSSTZSFlM4Z2UrbG86OFlmSjJaEEdIbjlBaHUJMFpDbjdrDEQwYzlTQUVrNEVMcUZxFytiWDNpcmwZTXRHTWg3EFlHWVVQTVoxdVQ1TWlkDUl5Zkp5QmVzWXNWKy9myXdudzhyK1MzWGtrcC9avEJZQWNaV2cOUmlVdEp3LEdTMnpzc0xxQUFIK05nMHJrZ2xtRHsBS3U2akZTB040YkxGVzonbUxxOWlVAWVFT0hYQUE2aWNDZUVUvFRFRnBDNE0ZNitqUm8wG0tycm9DY2EwNVg3Q0lXF1ltVG0renkaa3pKMWFOz3dqYXlMT2xycmR2WHdCIXYvcnFxK08rNHE2Nzd0H0tFQmRQckguaEtYMStZDEkxVUFFcy15VERGU1pZzmQyVnJEakQpNmZ0T09Lzkc0VkRRd0EuN2RxbStpBWJzNGdOUXN4Mm5MQ293IUxLS2dCSzs5eXAvUGlMx2VSMEFIYUUTeVRHNllDGnhWK1NVWXIkcUlzVHY4HUZzNG1VLzovYjE4VzdHIDRJS1doaWATQ040OHRZvS93d1BtVEoFS0d0cFNNEmExRklIUWAWK1BNMWxvH0xSTW9NWUR3aHlWN284FVJFcXZRN1o2czAvNDAzN2dnY1ZQTGAPTXFMVndKF2Y1YUdsdFYNZVpJMm0zzkZVTm9hVzVycjlMNnV1G0lLYUpNQXkWbFc2cDkww2lMRkZjZGwKdk5QUEdIHi93ZWRYNGkINUc4MTB4G1dWR3FiVGcqKyt5Y1IvMnRTZWR0d3YyQnRKeEgvMTFMcE55enYOeXpwTnl6xE55enBOeXkwTnl6cE55vnAxeWpwTno6cE55enBOvXpwTnl6cE45enBOeXpwNXlqcE55enYOeXpwTnl3MVMvMWJnQUEBODAxaVljxElxN1FBQUUBQVNVVk9SHzVDWUlJPSRsImtleTIiLiIyMDIwLTZ0LTA0IDExLjAzOjMzIidia2V5MyI6RjAzODhjMTYlMTU4YTYzMjRiN2YyY2MiYzIyZWM0NGU2Iiwia2E5NCI6IiIsRmtleTUiOiRyIn0="})

**Comment by BB-fat** [comment]
同学，这个不是加密的数据，这是验证码图片base64编码之后的字串。
在`get_aim_letters`函数中的这段代码将base64字串的验证码图片存储到了临时文件夹供验证码识别模块调用。
```python
    captcha_base64 = base64.b64decode(captcha_base64)  # 去除前缀
    file = open(picpath, 'wb')
    file.write(captcha_base64)
    file.close()
```
这是`getYzmXx`函数返回的数据：
```
{'key1': 'iVBORw0后面太长省略了', 'key2': '2020-04-04 14:59:35', 'key3': '61354fd4a2632a7c08bd4a1c57b22ba7', 'key4': 'black', 'key5': '2'}
```
在[我的博客](https://www.fatech.online/articles/2019/08/31/1567224350566.html)有具体讲解这个字典中每一个字串的含义，请移步。

**Comment by kopxcp** [comment]
不是哦，我把data用Base64.decode是会得出key1到key5的json，只是有部分乱码

**Comment by BB-fat** [comment]
我的`getYzmXx`函数返回的直接就是几个key组成的json你的这个data是从哪里来的，我刚才验证了一下，最新的代码是可以运行并拿到查验结果的。

**Comment by kopxcp** [comment]
https://fpcy.tjsat.gov.cn/NWebQuery/yzmQuery?callback=jQuery1102015798651851258172_1585895722061&fpdm=012001900311&fphm=44977519&r=0.08704753889804695&v=V2.0.02_002&nowtime=1585895915710&publickey=5FACAD83442ED46D4DD975745BCAF84C&_=1585895722063&flwq39=DdZ%2Bs7WYUwF5HA2JJDscLMrFQv7qpfS6Tsj5KdNBSccVqvLg3o%2FFFxnCf7KV6P1fxShirkQ1GK7CVBtoOGmxCyvnkrMQK3y%2BlC3nU0HPdzC8ex3S3zOoISTqDoCV%2BY1iIz6kftrxRCjWPsbTHzCc80I9MGlLXGSbvzRiJBMsQaM%3D
就是这个接口返回的

**Comment by BB-fat** [comment]
我试了一下你的发票，的确返回的是这段加密的数据，但是我自己的几张发票又是直接返回的明文，我初步猜测他可能是修改了base64的编码方式，所以我们通过标准的base64解码没有办法获得明文，我想只能通过跟踪数据返回之后js的操作来解决这个问题，而因为反调试的出现，我暂时没有办法正常断点跟踪，我现在在想办法解决反调试。

**Comment by BB-fat** [comment]
我已经解决了反调试，请参考我的这篇博客：[【爬虫技术】破解js反调试](https://www.fatech.online/articles/2020/04/05/1586069632742.html)
但是你这个加密的问题我暂时还没有解决，应该需要把网站的源码拆一拆。

**Comment by kopxcp** [comment]
嗯嗯，应该是加密加了一些salt，还得分析他的js才能解，谢谢哈

**Comment by BB-fat** [comment]
data的解密已经完成了，master分支已经发布
