### ISSUE TITLE
有些拿到的图片数据是data，好像是des加密的，但找不到key

### ISSUE THREAD

**Issue by fengfumin** [BB-fat/InvoiceSpider#17]
用base64转换data，还是乱码的
jQuery110205197960371738739_1586709306742({"data":"vyJrZXpxIjoizVZCT1Q3MEtHA29BQUUBTlNVzEVVZ0UBQUZvJUFBQWkDQUlBJUFDYjF0cGNBJUFJNUEsRVFWFjQydFAaQzFCETF4bGF4Um1LDWdCUm0halJCFVlKTVwvZEttyE1iSTUSR3pNNjhWM2kZRFJSFWtoQXY5WGFwITJSS0cGU2JHx1RYNE0vTVlZBUZWOG0WQ3FSzVBpQWslVzVzxTdJbTIWZDFuNC9MLzQ1WjNPLTdpN0cMdTZ1vWN5Wk1vODk5LXl6NS1vTzkzOy9mKzE5ZENxFkI1cEwKWFJxAklCM3UXY1dawEU0amxrdFNYNkZHSE55cjlrDlZ0cHtxYTF0EXRsYkcwa251MzdGdXYQaktsvnpSbWkkRFVUO21taGApbnpXIEFjSE03MUgxEk1iUGMPSThqO1hQdjIrN1Ftxk5LRVI1bGErxG9oK3kpMXdlIGcwSHUmZG54Nk5SbXkaM0Jmz01WTmIBRWZoxlh4bmwjZzgvH0VqeXtzLzFuwk9lbmoqcGRqJmticmxwZUxZNzdGN04OeHhzyGRpK2wtSFh2G3RYbk4Hcnk1MmduUUoLdjhmPy9iZjQkWGVQz2FmRWMhUDB1MVlqSXwadFllvCtlVTEQUnhPvTVZTjEGWVZGF1k4dXYQWTZPAS9Qc0QwT1BTBWM1U0kDMFFvNDdPVUgjSkJJHTV5QjwnVm5YIVROYmktOG01GkNsZHsPRDNyz3Bxc3t5dysrFy80TE4xL2xkvnFnd0cia21MFmMzZjMKN2l0GEQwQnE5RmpzO1dMZnF5TTZ4NE9kU0AGQlpsvG9jWTIzdGJ0F2JFdTsmbmdlDDVRaUkZYm9iGG8vMi0WamJjO3BQMC0WM29MEDdmdkF0UkZLyWZPN28hUGFVxE5oTGJxNS9mF1Npek84MVg0NVE3akMKL2J4N2VodnkGdEU5NXorSFYZNVlLGDdCYzMua215I3l4cVsnL2xpLGMxa2o5OUtjJjYwWUQaT1hXvUllQnYkY1NrxXBKc1BrMy92IGM2WXsPYWI3DmRIUk0zUFhPzmxQMW12ZHR0EjRRbHIPSncxFmdUSE4wNjR2x3ljSVRwa2lRJ1B6ODwTT3VSME95WGowblBBw2k2UDN0bEFLxjU3Z2kOaTExBmFpNGAnb0gxEzVZekNrTWVnDU9pZmh1Um8wvUdKYkIMeElWEXo2QUsjQnpTyS93dDMxelB6x0NNb0wWcFd4ITJnUm05dUJmN2locmctelRHB1FMUloQc29uJ3d1dTUSekE4BlFZU2QTOC9uP3V1RHsta2VXIzA3elkjVTdyDUFBVEAuL2g4BmRGOVYCb3d2yE44bjR2TWVZwDYybUoBczdSGkNoQm4yaFdsInpIdjMvaEkxyWtYUS0GazJ6NUE2VFoabEJsNUhWZFQ4Y01GGGV4ZHlzS1FvP0ZJRWIPdU5vzTlYak5wUjdQx1h2VVoNSElUzTE0NE0zd2VhHkwvWDYjRnFWBXlzNmM5czZ6MXVvWVIhQlNOyDlHNHU3NzFTyDEwQUgFT3c5E1hXOGoJZCtFJVFySnspaGdTyTd2cXUobDB1MzA0TkolWC9MFGR6aXQTSlJ5B0FqaXoXTFgwE2tvS2A1d240IUJkaGs6aThoDTlIRC0GeFpjNkhMNW4mN2tGGHhqbEEhd3dTyVM5aToFMWpBI1hDa1AucEFZN2lHL1EMSCttDHdIOXkETDFVEmYxUEkPNFdvx1o0WHYCQ3JGw3VrWDIKY0JwG3Z6ampyc291I0xPdmgObVpNMmhlMzZ3UE10ElllL3oiOFRQvkwzZWEqNzVPATZGbXoSYjl2zDdFK0cwN3BSHVAvWGIzVENGFDhBL1szVFpMGmU3RTUlUjA0BTUrTUEaRkw3GUZSTHN1djA0vkd1dXF3TXlJEERwSUsyY3AxIDY1cjUJWko3JmNNZnR0SVAyGG9BLzMCRGlnHXJvM2QOajVVyHE0VFUCT2t3JlhnMWguM0svE1I0RnYBMURINlZGTm85SjhKEmJPWkUrU1FSIUVOSXYsUGVSwk5Ea3sSV0t3BndZTEQmOHVzDTNkV0A4MjFHGFlvUHUaUHdUyzBiY2gqY0poIFRuSkEid28wEXNORjo6OEZMNGhubTMJMVhBGHptUmAFSTRkEmYvKzUPU0pFyDNnTkQjeFNOG0ZtSHMsMTA5IjQ0c3J0RnpUFkdrT0UOU1pYMnFQS3sSZlpjGUFmTUlvcGVYElI1Nnp1a3Z3EUhia2INZEtBGUVINFUGd0lRIVJmd1QwZzhkxFNzY3I6T2NlzW9NREwJbkRnFm9QY24KeU5sJStvemw5NGs3z05kTEV1RjJBzVlnNUMOU3ZpyVFsQkFxQ0RpH3RFTXtrQ1l0MldDL3pvSDY0AE5VYTMwaUNPyVFTRjUndS9rFkw3dmNzM0FCyVRkSUEDeWF4JWpVaU8DMXQwE3JJTk0NekhKO0ZGSUAMZDlUEmhEZXwXNVVNInFqK1widlR4EnM2SWwrU3Jwy1FqMXkJbElKIVZTQVkZMXRzFHF3emsUZkpFDnYrUk0DRWNKBzNGZmwGNmttE3c4K1Uwa2lox0JnNE8qcG91HjVYWVlzc0UvAlpjT0B5cGp4NWNSYXRxQTdnIUZNd3YYYlVDGmlTRzMFcnpoNEd1YXANT05HNzlnRTwwQlZrFWR1bWoPVFF2HXJua3YBUnlHEXhQQzATN2dTBm9vREgFUVpLxkpVZXZzT2VRwi9DSVIMVjhYF3U0TU0mMUxtHy9QRTsDNDA4M2hVelQFUkNvzDZZd1wwdjAxM3VRVXI5eVJZAXVTaGUtdVNWDTJLMUAzVUdwyjh5RUIGeXlIwk91Y28KRlhTMUlBVlwuaDQwB2pnUDUEN24yGW9BQUMwQ01PwWxlb1YCQVgzFDVuVG8NSGwwE1hFZXInWHhwFHRSeDUaOWtDGm56VCgDcWZmNE1NRmQGdFVCy3BzZkpvdk1kzjVRaEQKZit0DlZESXsqNzEyLG1PZ1UIRWNWNjFVcDICUWZrwWhra1wUSTZDA2hBQnonb1NlDmR5eGEnS21qAHRNWjAucktPHzNkazRramszDEVGS08QZ2Q1MDFuOU4DdEVBJklnSWQEaDg0DFluVzQwaG5ywG5QOGRyOHFOz0xKSFITeVg0EEdSY0ktT1NnykpKU0Byckg5AFV6KzIhRFBnE1ovTUwMYnUzGFRZb0EpMGVRIDF4RGR1NUNoFXBlQUU1VHQyEzUxYTEhMWQ0DUNIbVwhdVpBETRXeUsjRENSJTFsSDULUVVGI1ZNMUl2cmZIBTFZWnRyUHdGzThWd2F5bmFOy2dvYkI3OW5GAEJLakEnYUhPNXZ3M2k1emhZAnZhQW4Peldwy3l0bFwSYXY0w1l3ZkEaRUtBLHhScVkNR0UzyFBtRUMFamVNwTJMcVZwQlIzNTNPbnANb01IEVNEODohbENpy3pqQ21wSkhCG0hLVHMOTWhXxngxWU55MmtwP0k1WVoSb04vFHo1aWMSN25Fw1pPQWAKZlRkAE9ERUAKSnRxDFluTU84S0xoO3NkSXAVQ0JZJ0dTYmQVWXMzJjV4K3R0NWlGIFRHVG4jWEpIzVdIdjZwNHZYwTBLS3kSLzVmBjZoUjMuWjIwDDJQdVNvcGhSDjMxZ3MXak5pxmh1N1E0SXZYGGQxR2MEYlZUFU9KSVQJTmhwNVhFVVsQekhnxzNmdnIzUjdFH2g0b2gMUUJNM0E1QkQjV0JILVVHZlkkTEZuy1RnRVIoSzFpvnM5VnAtV0JmO1Y1Q1F4NEdkxDZlRkw6ek1CBmNFUzFvdE5MAStLdkh0by84ymZKUHMZUWhlxWg3Z1EUaHN0A0ZENHsuN2k3EUhuaFUkSEdWHHl2dzsaejNNFzdiZFt3SGpZDkkrTW5reTV3DFNPVGl4MG82MWxRakk2NXpUzjB4eE42U1BmBTQrTjYpTTZ6P1djbjELMm1IAFZsM1ZrRkdSMG9uQjIlejZEAzYvOVUUZ1dCPzNZdm4VRSs3w1B6cjUubE5BMVBobS0vVFo4AEdLS0kjendzHDJ6M3Mocm9lIHd5bXwyRWY1IzIxNnYVajBjNTlvek4OOCsyFFFqdjsEZlcvI2RaSDAMdjhBJUFBQVMVVk9SHzVDWUoJPSIsRmtleTRiOiIyNDIwLTZ0LTEzRDEyOjN0OjAyRiwia2E5MyI6RjEzNTolNTBiMTA3YzV3NDEyM2ZmNDxyNGM0BTNmZjJwIiwiz2V5NCR6IjAzRiwia2E5NSI6RjIifQ=="})

**Comment by BB-fat** [comment]
请查看我昨天更新的master分支，已经有了解密的方法，它这里用的不是通用的Base64编码，加盐了。
具体解密的代码在：https://github.com/BB-fat/InvoiceSpider/blob/master/scripts/yzm.py      312行
```
    if res.get("data") != None:
        # 解密data数据
        ctx = execjs.compile(js)
        res = json.loads(ctx.call("decryptData", res["data"], nowtime))
```

**Comment by BB-fat** [comment]
解决了吗？解决了我就关了

**Comment by fengfumin** [comment]
这个解决了，谢谢
