### ISSUE TITLE
验证码正常请求，返回发票信息异常

### ISSUE THREAD

**Issue by ruanzupan** [BB-fat/InvoiceSpider#18]
'3200192130', '33393793', "20191214", "7522.12"     
这个发票一直返回{"key1": "005", "key2": "", "key3": "0"}
官网能正常查询出发票数据。不知道是否是加密之类的问题？

**Comment by BB-fat** [comment]
对的，部分发票在查验的时候增加了flwq39这个参数的校验，所以查不出来，这个比较复杂，我还在破解

**Comment by ruanzupan** [comment]
好的，持续关注。^v^

**Comment by BB-fat** [comment]
Duplicate of #14
