### ISSUE TITLE
如何破解浏览器的反调试设置

### ISSUE THREAD

**Issue by wsqy** [BB-fat/InvoiceSpider#19]
4.28测试mitmproxy启动并配置代理后，国税发票查验网站不能打开，其他网站正常打开。关闭代理后国税网站打开正常

**Comment by BB-fat** [comment]
这个可能和你的浏览器配置有关系，不过忘了这个吧，有一个更简单的办法：
* 正常打开网站之后禁用断点
* 然后继续运行
* 打开console输入以下代码
```js
for(var i=0;i<99999;i++){
    window.clearInterval(i)
}
```
* 然后再启动断点就可以正常调试了

**Comment by wsqy** [comment]
我按照这个方法试了一下，发现还是很卡，不知道是不是我的方式哪里错了，请指教。
(浏览器: chrome55,网站指定版本)
1. 打开 [国税网站](https://inv-veri.chinatax.gov.cn/index.html)
2. F12打开开发者功能，会自动跳转到 source 栏目
3. 在source栏目  按ctrl+F8关闭断点功能
4. 切换到console，输入`clearInterval`代码
5. 切换到source，按ctrl+F8开启断点调试功能

以上操作后，在发票代码及发票号码栏目输入，发现还是卡到不行，不知道是那步操作不对呢？？

**Comment by BB-fat** [comment]
应该少了一步，在3后需要点那个继续，不要让断点卡在那里，然后在进行第4步

**Comment by wsqy** [comment]
继续按钮是哪一个呢？是F8的Resume script execution  还是F11的 step into next function call

**Comment by BB-fat** [comment]
<img width="121" alt="image" src="https://user-images.githubusercontent.com/45072480/80466011-83458280-896e-11ea-9292-f8c35694de64.png">

**Comment by wsqy** [comment]
嗯，这是F8的Resume script execution，按这个操作之后还是感觉卡到不行

**Comment by wsqy** [comment]
关闭浏览器,重启下电脑，现在完全不卡了，多谢！！
