### ISSUE TITLE
大佬，你这个项目适用于Python那个版本啊？

### ISSUE THREAD

**Issue by shimachao** [BB-fat/InvoiceSpider#4]
python 3.7 和 3.8 可以吗

**Comment by BB-fat** [comment]
我这边用的是Python3.7.3，主要代码python3就可以，主要是那些依赖包得能正常安装。

**Comment by shimachao** [comment]
> 我这边用的是Python3.7.3，主要代码python3就可以，主要是那些依赖包得能正常安装。

多谢告知，我测试的时候发现 Python 3.8 不行，因为tensorflow装不了

**Comment by BB-fat** [comment]
验证码识别的部分是我的同学帮我完成的，他告诉我一定要按照依赖的版本安装，否则可能出现一些兼容性问题
