### ISSUE TITLE
大佬，pricd_prijm.py 有语法错误

### ISSUE THREAD

**Issue by shimachao** [BB-fat/InvoiceSpider#5]
35，48行的a.substring(2, 3)改成a[2:3]。python的字符串没有substring方法。
还有
def pricd(a, t, s):
    c = ctx.call("o", a)
    if c == "1100":
        s = encrypt(a + moveTo(t) + s).upper()
        s = encrypt(moveTo(s) + a).upper()
。。。
a+moveTo(t)+s 报错，貌似因为你直接用+连接整数和字符串，在Python里面不合法的。
感觉你对Python不熟悉，在用另一门的语言的语法写Python

**Comment by BB-fat** [comment]
感谢你提出这个问题！
pricd函数是我直接从js版的pricd函数直接替换字符更改的，当时没有注意python应该直接用分片的问题，后来也没有发现是因为我用来测试的发票集不够全面，我用来测试的发票大多来源于京东，都是北京的发票，程序只运行了这个分支：
```
    if c == "1100":
        s = encrypt(a + moveTo(t) + s).upper()
        s = encrypt(moveTo(s) + a).upper()
```
所以没有触发过`substring`的异常，至于你说的`a+moveTo(t)+s`的异常，我这边没有复现，我的所有函数传参都是字符串，你看一下是不是你那边把某个参数用了整型。
我在[v2.1](https://github.com/BB-fat/InvoiceSpider/releases/tag/v2.1)版本中修复了substring的问题，并且给几个主要函数增加了类型说明，感谢提出宝贵的建议！
