### ISSUE TITLE
TensorFlow的warning日志怎么关闭呢？

### ISSUE THREAD

**Issue by shimachao** [BB-fat/InvoiceSpider#7]
每次运行都会输出下面的warning日志：
C:\Users\xxx\.virtualenvs\InvoiceSpider\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\xxx\.virtualenvs\InvoiceSpider\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])

我已经在 sdk.py 中加了
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
但还是有很多TensorFlow的warning日志输出

**Comment by BB-fat** [comment]
这个我也不知道，我对TensorFlow不是很熟悉。
