### ISSUE TITLE
感谢之前逆向工程的blog提供经验

### ISSUE THREAD

**Issue by starboyhz** [BB-fat/InvoiceSpider#9]
去年最初入手是参考你的逆向工程blog做的，后面花了2个月已优化到秒级响应，
有问题可以沟通，目前验证码识别率92%+，优化空间除了提高识别验证码率外，把python执行的js脚本转化成python脚本也是一块。starboy_hz@sina.com

**Comment by BB-fat** [comment]
Hi，感谢你关注我的项目，我非常惊讶你能将验证码识别率提高到惊人的92%，想请教一下你是怎么做到的。
我和伙伴的方法是找到一个近似税务平台验证码的java验证码框架然后训练，但是该框架没有中文字符，再加上和税务平台验证码的细微差别，最终的识别率只能达到22%，很难再有提升。

P.S：你的建议非常好——将js转换成python实现，我计划有时间做一下这部分的升级，你是否愿意加入我的项目？

期待您的回复
